using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventCatalogAPI.Domains
{
    public class EventItem
    {
        public int Id { get; set; } //EventId will be Autogenerated primary key
        public string EventName { get; set; }
        public decimal EventCost { get; set; }

        public string EventDescription { get; set; }

        public string EventAddress { get; set; }
        public string EventCity { get; set; }
        public string EventState { get; set; }
        public int EventZip { get; set; }
        public bool EventFavorite { get; set; } // EventFavorite will be set to False by default
        public int EventTicketsAvailable { get; set; } // Total tickets available will be set to 100 by default

        public string EventStartDate { get; set; }
        public string EventStartTime { get; set; }
        

        public string EventEndDate { get; set; } // example 07/12/2019
        public string EventEndTime { get; set; }

        public string EventPictureUrl { get; set; } //picture for the Event to be created
        public string EventUrl { get; set; } // website of the hosting party


        //This is tied to  and EventCategory (like Catalog Type
        public int EventCategoryId { get; set; } //foreign key

        //this is tied to EventVenue
        public int EventVenueId { get; set; } //foreign key

        public virtual EventCategory EventCategory { get; set; } // EventCategoryID will become foreign key and this statement links it

        public virtual EventVenue EventVenue { get; set; } // EventVenueId will become foreign key and this statement links it



    }
}
